name: Build and Deploy to Render

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy-render:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Step 2: Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      # Step 3: Cache npm dependencies to speed up builds
      - name: Cache npm dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('server/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # Step 4: Install npm dependencies
      - name: Install Dependencies
        run: npm install
        working-directory: ./server

      # Step 5: Run tests (commented out due to lack of time)
      # - name: Run Tests
      #   run: npm test
      #   working-directory: ./server

      # Step 6: Build the project
      - name: Build Project
        run: npm run build
        working-directory: ./server

      # Step 7: Deploy to Render
      - name: Deploy to Render
        uses: render-actions/deploy@v1
        with:
          service-id: ${{ secrets.RENDER_PROJECT_ID }}
          api-key: ${{ secrets.RENDER_AUTH_TOKEN }}
